CREATE TABLE IF NOT EXISTS tbl_records (
    id INT(11) AUTO_INCREMENT PRIMARY KEY,
    amount DOUBLE DEFAULT NULL,
    note MEDIUMTEXT,
    category_id INT(11),
    date_created DATETIME DEFAULT CURRENT_TIMESTAMP,
    date_updated DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    active_status ENUM('0', '1') DEFAULT '1' NOT NULL,
    FOREIGN KEY (category_id) REFERENCES tbl_categories(id) ON DELETE SET NULL
)ENGINE=InnoDB
