CREATE TABLE IF NOT EXISTS tbl_debtrecords (
    id INT(11) AUTO_INCREMENT PRIMARY KEY,
    debtor_id INT(11),
    amount DOUBLE DEFAULT NULL,
    note TEXT,
    date_created DATETIME DEFAULT CURRENT_TIMESTAMP,
    date_updated DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    active_status ENUM('0', '1') DEFAULT '1' NOT NULL,
    FOREIGN KEY (debtor_id) REFERENCES tbl_debtors(id) ON DELETE SET NULL
)ENGINE=InnoDB